# Generated by Django 5.2.2 on 2025-06-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payroll_date', models.DateField()),
                ('original_calculation', models.JSONField()),
                ('corrected_calculation', models.JSONField(blank=True, null=True)),
                ('difference', models.JSONField(blank=True, null=True)),
                ('fps_submitted_original', models.BooleanField(default=False)),
                ('fps_submitted_corrected', models.BooleanField(default=False)),
            ],
        ),
    ]
