# Generated by Django 5.2.2 on 2025-06-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OverpaymentCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tax_year', models.CharField(max_length=10)),
                ('month_op_occurred', models.CharField(max_length=20)),
                ('taxable_pay_ytd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_paid_ytd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prev_tax_ni_deducted', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_data', models.JSONField()),
                ('due_data', models.JSONField()),
                ('difference_data', models.JSONField()),
            ],
        ),
    ]
